package com.softtek.determinacion.constant;

public final class Propiedades {

    public static final String C_V_RJP_MSG_73_97 = "SIN DERECHO, TRABAJADOR CON RJP, DE CONFORMIDAD CON LOS ART 1 Y 2 DEL R\u00c9GIMEN DE JUBILACIONES Y PENSIONES ";
    public static final String C_RJP_CVE_FUN_73 = "75";
    public static final String C_RJP_CVE_FUN_97 = "76";
    public static final String V_RJP_CVE_FUN_73 = "77";
    public static final String V_RJP_CVE_FUN_97 = "78";
    public static final String C_V_RJP_FUN_73_97 = "TRABAJADOR CON RJP ART 1 Y 2 ";

    public static final String C_SUSCEPTIBILIDAD_CVE_OBS_73 = "71";
    public static final String C_SUSCEPTIBILIDAD_CVE_OBS_97 = "72";
    public static final String V_SUSCEPTIBILIDAD_CVE_OBS_73 = "73";
    public static final String V_SUSCEPTIBILIDAD_CVE_OBS_97 = "74";
    public static final String C_V_SUSCEPTIBILIDAD_OBS_73_97 = "TRABAJADOR SUSCEPTIBLE A RJP DE CONFORMIDAD CON EL ARTICULO 1 y 2 DEL R\u00c9GIMEN DE JUBILACIONES Y PENSIONES ";

    public static final String C_RETIROTOTAL_MSG25_97 = "SIN DERECHO EXISTE MARCA DE RETIRO TOTAL ART 154, 3ER P\u00c1RRAFO LSS 97 ";
    public static final String C_RETIROTOTAL_CVE_FUN_97 = "04";
    public static final String C_RETIROTOTAL_FUN_97 = "RETIRO TOTAL ART 154, 3ER P\u00c1RRAFO LSS 97 ";
    public static final String C_RETIROTOTAL_CVE_OBS_97 = "92";
    public static final String C_RETIROTOTAL_OBS_97 = "SIN DERECHO EXISTE MARCA DE RETIRO TOTAL ";
    public static final String V_RETIROTOTAL_MSG26_97 = "SIN DERECHO EXISTE MARCA DE RETIRO TOTAL ART 162 2DO P\u00c1RRAFO LSS 97 ";
    public static final String V_RETIROTOTAL_CVE_FUN_97 = "16";
    public static final String V_RETIROTOTAL_FUN_97 = "RETIRO TOTAL ART 162, 2DO P\u00c1RRAFO LSS 97 ";
    public static final String V_RETIROTOTAL_CVE_OBS_97 = "96";
    public static final String V_RETIROTOTAL_OBS_97 = "SIN DERECHO EXISTE MARCA DE RETIRO TOTAL ";

    public static final String C_ASEGURADOVIGENTE_MSG27_73 = "SIN DERECHO, EL ASEGURADO SE ENCUENTRA VIGENTE, NO CUMPLE CON LOS ART 143 y 145, FRACC III LSS 73 ";
    public static final String C_ASEGURADOVIGENTE_MSG28_97 = "SIN DERECHO, EL ASEGURADO SE ENCUENTRA VIGENTE, NO CUMPLE CON EL ART 154, 1ER P\u00c1RRAFO LSS 97 ";
    public static final String C_ASEGURADOVIGENTE_CVE_FUN_73 = "94";
    public static final String C_ASEGURADOVIGENTE_FUN_73 = "ASEGURADO VIGENTE NO CUMPLE ART 143 Y 145 FRACCI\u00d3N III LSS 73 ";
    public static final String C_ASEGURADOVIGENTE_CVE_FUN_97 = "32";
    public static final String C_ASEGURADOVIGENTE_FUN_97 = "ASEGURADO VIGENTE NO CUMPLE ART. 154  1ER P\u00c1RRAFO LSS 97 ";
    public static final String V_ASEGURADOVIGENTE_MSG56_73 = "SIN DERECHO, EL ASEGURADO SE ENCUENTRA VIGENTE, NO CUMPLE CON EL ART 141 LSS 73 ";
    public static final String V_ASEGURADOVIGENTE_MSG18_97 = "SIN DERECHO, EL ASEGURADO SE ENCUENTRA VIGENTE, NO CUMPLE CON EL ART 163 LSS 97 ";
    public static final String V_ASEGURADOVIGENTE_CVE_FUN_73 = "94";
    public static final String V_ASEGURADOVIGENTE_FUN_73 = "ASEGURADO VIGENTE NO CUMPLE ART. 141 LSS 73 ";
    public static final String V_ASEGURADOVIGENTE_CVE_FUN_97 = "07";
    public static final String V_ASEGURADOVIGENTE_FUN_97 = "ASEGURADO VIGENTE ";

    public static final String C_NOCUMPLEEDAD_MSG29_73 = "SIN DERECHO, ASEGURADO NO CUMPLE CON LA EDAD REQUERIDA, DE CONFORMIDAD CON EL ART 143 y 145 FRACC III LSS 73 ";
    public static final String C_NOCUMPLEEDAD_MSG30_97 = "SIN DERECHO, ASEGURADO NO CUMPLE CON LA EDAD REQUERIDA, DE CONFORMIDAD CON EL ART 154, 1ER P\u00c1RRAFO LSS 97 ";
    public static final String C_NOCUMPLEEDAD_CVE_FUN_73 = "21";
    public static final String C_NOCUMPLEEDAD_FUN_73 = "NO APLICACI\u00d3N DEL ART. 143 Y 145 FRACC. II LEY SS 73 ";
    public static final String C_NOCUMPLEEDAD_CVE_FUN_97 = "35";
    public static final String C_NOCUMPLEEDAD_FUN_97 = "APLICACI\u00d3N DEL ART.154 1ER.P\u00c1RRAFO LEY SS.1997 ";
    public static final String V_NOCUMPLEEDAD_MSG31_73 = "SIN DERECHO, ASEGURADO NO CUMPLE CON LA EDAD REQUERIDA, DE CONFORMIDAD CON EL ART 138 LSS 73 ";
    public static final String V_NOCUMPLEEDAD_MSG32_97 = "SIN DERECHO, ASEGURADO NO CUMPLE CON LA EDAD REQUERIDA,  DE CONFORMIDAD CON EL ART 162, 1ER P\u00c1RRAFO LSS 97 ";
    public static final String V_NOCUMPLEEDAD_CVE_FUN_73 = "20";
    public static final String V_NOCUMPLEEDAD_FUN_73 = "NO CUMPLE CON LO DISPUESTO ART. 138 LSS 73 ";
    public static final String V_NOCUMPLEEDAD_CVE_FUN_97 = "25";
    public static final String V_NOCUMPLEEDAD_FUN_97 = "NO, APLICACI\u00d3N DEL ART.162 1ER.P\u00c1RRAFO LEY SS.1997 ";

    public static final String C_NOSEMANASRECONOCIDAS_MSG33_73 = "SIN DERECHO, NO CUENTA CON AL MENOS 500 SEMANAS COTIZADAS, DE CONFORMIDAD CON EL ART\u00cdCULO 145 FRACC I LSS. 73. ";
    public static final String C_NOSEMANASRECONOCIDAS_MSG34_97 = "SIN DERECHO, NO CUENTA CON LAS SEMANAS COTIZADAS REQUERIDAS, DE CONFORMIDAD CON EL ART 154 2DO P\u00c1RRAFO LSS 97 ";
    public static final String C_NOSEMANASRECONOCIDAS_MSG35_97 = "CON OPCI\u00d3N A RETIRO DEL SALDO DE SU CUENTA INDIVIDUAL DE CONFORMIDAD CON EL ART 154 3ER P\u00c1RRAFO ";
    public static final String C_NOSEMANASRECONOCIDAS_CVE_FUN_73 = "98";// posible 95
    public static final String C_NOSEMANASRECONOCIDAS_FUN_73 = "CUMPLE CON 500 SEMANAS   ART. 145 LEY S.S. 73 ";
    public static final String C_NOSEMANASRECONOCIDAS_CVE_FUN_97 = "33";
    public static final String C_NOSEMANASRECONOCIDAS_FUN_97 = "REUNE TIEMPO DE ESPERA ART 154 2DO P\u00c1RRAFO LSS97 ";
    public static final String C_NOSEMANASRECONOCIDAS_CVE_OBS_97 = "04";
    public static final String C_NOSEMANASRECONOCIDAS_OBS_97 = "OPCI\u00d3N A RETIRO APLIC. ART.154 3ER.PARR.LEY SS ";
    public static final String V_NOSEMANASRECONOCIDAS_MSG36_73 = "SIN DERECHO, NO CUENTA CON AL MENOS 500  SEMANAS COTIZADAS , DE CONFORMIDAD CON EL ART 138 LSS 73. ";
    public static final String V_NOSEMANASRECONOCIDAS_MSG37_97 = "SIN DERECHO, NO CUENTA CON LAS SEMANAS COTIZADAS REQUERIDAS, DE CONFORMIDAD CON EL ART 162 1ER P\u00c1RRAFO LSS 97 ";
    public static final String V_NOSEMANASRECONOCIDAS_MSG38_97 = "CON OPCI\u00d3N A RETIRO DEL SALDO DE SU CUENTA INDIVIDUAL DE CONFORMIDAD CON EL ART 162 2DO P\u00c1RRAFO ";
    public static final String V_NOSEMANASRECONOCIDAS_CVE_FUN_73 = "01";
    public static final String V_NOSEMANASRECONOCIDAS_FUN_73 = "NO CUMPLE CON LAS 500   SEMS.ART.138 LEY S.S.73 ";
    public static final String V_NOSEMANASRECONOCIDAS_CVE_FUN_97 = "25";
    public static final String V_NOSEMANASRECONOCIDAS_FUN_97 = "APLICACI\u00d3N DEL ART.162 1ER. P\u00c1RRAFO LEY SS.1997 ";
    public static final String V_NOSEMANASRECONOCIDAS_CVE_OBS_97 = "16";
    public static final String V_NOSEMANASRECONOCIDAS_OBS_97 = "OPCI\u00d3N A RETIRO APLIC. ART.162 2DO.P\u00c1RRAFO LEY SS 97 ";

    public static final String C_PENSIONGARANDESCUENTOINCAPACIDAD_MSG39_97 = "CON DERECHO, PENSI\u00d3N GARANTIZADA, DE CONFORMIDAD CON EL ART 153 2DO P\u00c1RRAFO LSS 97 ";
    public static final String C_PENSIONGARANDESCUENTOINCAPACIDAD_CVE_FUN_97 = "07";
    public static final String C_PENSIONGARANDESCUENTOINCAPACIDAD_FUN_97 = "ART 153 2DO P\u00c1RRAFO ";
    public static final String C_PENSIONGARANDESCUENTOINCAPACIDAD_CVE_OBS_97 = "62";
    public static final String C_PENSIONGARANDESCUENTOINCAPACIDAD_OBS_97 = "CON DERECHO, PENSI\u00d3N GARANTIZADA ART 153 2DO P\u00c1RRAFO LSS 97 ";
    public static final String V_PENSIONGARANDESCUENTOINCAPACIDAD_MSG40_97 = "CON DERECHO, PENSI\u00d3N GARANTIZADA, DE CONFORMIDAD CON EL ART 153 2DO P\u00c1RRAFO LSS 97 ";
    public static final String V_PENSIONGARANDESCUENTOINCAPACIDAD_CVE_FUN_97 = "07";
    public static final String V_PENSIONGARANDESCUENTOINCAPACIDAD_FUN_97 = "ART 153 2DO P\u00c1RRAFO ";
    public static final String V_PENSIONGARANDESCUENTOINCAPACIDAD_CVE_OBS_97 = "62";
    public static final String V_PENSIONGARANDESCUENTOINCAPACIDAD_OBS_97 = "CON DERECHO, PENSI\u00d3N GARANTIZADA ART 153 2DO P\u00c1RRAFO LSS 97 ";

    public static final String C_V_SINDERECHOREGIMEN_MSG41_73_97 = "NO TIENE DERECHO A ELECCI\u00d3N DE R\u00c9GIMEN. NO APLICACI\u00d3N ART. TERCERO Y CUARTO TRANSITORIO LSS 1997 ";
    public static final String C_V_SINDERECHOREGIMEN_CVE_FUN_73_97 = "48";
    public static final String C_V_SINDERECHOREGIMEN_FUN_73_97 = "APLICACI\u00d3N DE ARTS. 3 Y 4 TRANS. LSS 97 ";

    public static final String C_FUERACONSERVACIONDERECHOS_MSG42_73 = "SIN DERECHO, ASEGURADO SE ENCUENTRA FUERA DE LA CONSERVACI\u00d3N DE DERECHOS, DE CONFORMIDAD CON EL ART 182 LSS 73 ";
    public static final String C_FUERACONSERVACIONDERECHOS_CVE_FUN_73 = "56";
    public static final String C_FUERACONSERVACIONDERECHOS_FUN_73 = "NO CUMPLE CON EL ART. 182 LEY S.S. 1973 ";
    public static final String V_FUERACONSERVACIONDERECHOS_MSG43_73 = "SIN DERECHO, ASEGURADO SE ENCUENTRA FUERA DE LA CONSERVACI\u00d3N DE DERECHOS, DE CONFORMIDAD CON EL ART182 LSS 73 ";
    public static final String V_FUERACONSERVACIONDERECHOS_CVE_FUN_73 = "56";
    public static final String V_FUERACONSERVACIONDERECHOS_FUN_73 = "NO CUMPLE CON EL ART. 182 LEY S.S. 1973 ";

    public static final String C_RECONOCIMIENTOSDERCHOS_MSG44_73 = "SIN DERECHO, CON SEMANAS INSUFICIENTES PARA EL RECONOCIMIENTO DE SEMANAS, DEBER\u00c1 CUMPLIR CON LO ESTABLECIDO EN EL ART 145 FRACC I Y 183 LSS 73 ";
    public static final String C_RECONOCIMIENTOSDERCHOS_CVE_FUN_73 = "21";
    public static final String C_RECONOCIMIENTOSDERCHOS_FUN_73 = "NO CUMPLE CON LO DISPUESTO ART. 145 FRACCI\u00d3N I Y 183 LSS 73 ";
    public static final String V_RECONOCIMIENTOSDERCHOS_MSG45_73 = "SIN DERECHO, CON SEMANAS INSUFICIENTES PARA EL RECONOCIMIENTO DE SEMANAS, DEBER\u00c1 CUMPLIR CON LO ESTABLECIDO EN EL ART 138 Y 183 LSS 73 ";
    public static final String V_RECONOCIMIENTOSDERCHOS_CVE_FUN_73 = "20";
    public static final String V_RECONOCIMIENTOSDERCHOS_FUN_73 = "NO CUMPLE CON LO DISPUESTO ART. 138 Y 183 LSS 73 ";

    public static final String C_CONDERECHOPRESTACIONESPECIE_MSG46_97_SM = "SIN DERECHO, NO CUENTA CON LAS SEMANAS RECONOCIDAS REQUERIDAS, DE CONFORMIDAD CON EL ART 154  2DO P\u00c1RRAFO LSS 97, AUNQUE CUMPLE CON 750 SEMANAS RECONOCIDAS ";
    public static final String C_CONDERECHOPRESTACIONESPECIE_MSG47_97_SM = "CON DERECHO  A LAS PPRESTACIONES EN ESPECIE DEL SEGURO DE ENFERMEDADES Y MATERNIDAD, DE CONFORMIDAD CON EL ART 154 ÚLTIMO P\u00c1RRAFO ";
    public static final String C_CONDERECHOPRESTACIONESPECIE_CVE_FUN_97_SM = "33";
    public static final String C_CONDERECHOPRESTACIONESPECIE_FUN_97_SM = "A PRT. EN PECIE ARTICULO 154  4TO P\u00c1RRAFO  LEY 97 ";
    public static final String C_CONDERECHOPRESTACIONESPECIE_CVE_OBS_97_SM = "04";
    public static final String C_CONDERECHOPRESTACIONESPECIE_OBS_97_SM = "OPCI\u00d3N A RETIRO APLIC. ART.154 3ER.PARR.LEY SS ";
    public static final String V_CONDERECHOPRESTACIONESPECIE_MSG48_97_SM = "SIN DERECHO, NO CUENTA CON LAS SEMANAS RECONOCIDAS REQUERIDAS, DE CONFORMIDAD CON EL ART 162 1ER P\u00c1RRAFO LSS 97, AUNQUE CUMPLE CON 750 SEMANAS RECONOCIDAS ";
    public static final String V_CONDERECHOPRESTACIONESPECIE_MSG49_97_SM = "CON DERECHO  A LAS PRESTACIONES EN ESPECIE DEL SEGURO DE ENFERMEDADES Y MATERNIDAD, DE CONFORMIDAD CON EL ART 162 2DO P\u00c1RRAFO ";
    public static final String V_CONDERECHOPRESTACIONESPECIE_CVE_FUN_97_SM = "24";
    public static final String V_CONDERECHOPRESTACIONESPECIE_FUN_97_SM = "A PRESTACIONES EN ESP. ART. 162 2DO. P\u00c1RRAFO ";
    public static final String V_CONDERECHOPRESTACIONESPECIE_CVE_OBS_97_SM = "04";
    public static final String V_CONDERECHOPRESTACIONESPECIE_OBS_97_SM = "OPCI\u00d3N A RETIRO APLIC. ART.154 3ER.PARR.LEY SS ";

    public static final String C_SINDERECHOPRESTACIONESPECIE_MSG50_97_SM = "SIN DERECHO, NO CUENTA CON AL MENOS 750 SEMANAS RECONOCIDAS, DE CONFORMIDAD CON EL ART 154, 2DO P\u00c1RRAFO LSS 97 ";
    public static final String C_SINDERECHOPRESTACIONESPECIE_MSG51_97_SM = "NO CUMPLE CON EL MINIMO REQUERIDO PARA GOZAR DE LAS PRESTACIONES EN ESPECIE, CON FUNDAMENTO EN EL ART 154 ÚLTIMO P\u00c1RRAFO 97 ";
    public static final String C_SINDERECHOPRESTACIONESPECIE_MSG52_97_SM = "CON OPCI\u00d3N A RETIRO DEL SALDO DE SU CUENTA INDIVIDUAL DE CONFORMIDAD CON EL ART 154 3ER P\u00c1RRAFO ";
    public static final String C_SINDERECHOPRESTACIONESPECIE_CVE_FUN_97_SM = "33";
    public static final String C_SINDERECHOPRESTACIONESPECIE_FUN_97_SM = "REUNE TIEMPO DE ESPERA ART 154 2DO PARR LSS97 NO PRT. EN PECIE NO CUMPLE ARTICULO 154  LEY 97 ";
    public static final String C_SINDERECHOPRESTACIONESPECIE_CVE_OBS_97_SM = "04";
    public static final String C_SINDERECHOPRESTACIONESPECIE_OBS_97_SM = "OPCI\u00d3N A RETIRO APLIC. ART.154 3ER.PARR.LEY SS ";
    public static final String V_SINDERECHOPRESTACIONESPECIE_MSG53_97_SM = "SIN DERECHO, NO CUENTA CON AL MENOS 750 SEMANAS RECONOCIDAS , DE CONFORMIDAD CON EL ART 162  1ER P\u00c1RRAFO LSS 97 ";
    public static final String V_SINDERECHOPRESTACIONESPECIE_MSG54_97_SM = "NO CUMPLE CON EL MINIMO REQUERIDO PARA GOZAR DE LAS PRESTACIONES EN ESPECIE, CON FUNDAMENTO EN EL ART 162 2DO P\u00c1RRAFO LSS 97 ";
    public static final String V_SINDERECHOPRESTACIONESPECIE_MSG55_97_SM = "CON OPCI\u00d3N A RETIRO DEL SALDO DE SU CUENTA INDIVIDUAL DE CONFORMIDAD CON EL ART 162 2DO P\u00c1RRAFO";
    public static final String V_SINDERECHOPRESTACIONESPECIE_CVE_FUN_97_SM = "24";
    public static final String V_SINDERECHOPRESTACIONESPECIE_FUN_97_SM = "NO CUMPLE CON EL ART. 162 SEGUNDO P\u00c1RRAFO ";
    public static final String V_SINDERECHOPRESTACIONESPECIE_CVE_OBS_97_SM = "16";
    public static final String V_SINDERECHOPRESTACIONESPECIE_OBS_97_SM = "OPCI\u00d3N A RETIRO APLIC. ART.162 2DO.PARR.LEY SS ";

}
